import type { Metadata } from 'next';
import { Fredoka } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/themes/theme.provider';

const fredoka = Fredoka({
  variable: '--font-fredoka-sans',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Teritage',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fredoka.variable} antialiased`}>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
