import type { Metadata } from 'next';
import { Fredoka } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/themes/theme.provider';
import { Toaster as Sonner } from '@/components/ui/sonner';
import TanstackProvider from '@/context/tanstack-provider';
import '@rainbow-me/rainbowkit/styles.css';

const fredoka = Fredoka({
  variable: '--font-fredoka-sans',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Teritage',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fredoka.variable} antialiased`}>
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <TanstackProvider>
            {children}
            <Sonner richColors duration={2000} closeButton position="top-right" />
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
